
name: Install, Build & Run Jest

on: [push]
env:
  CHILD_CONCURRENCY: 1
  NODE_ENV: test
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Branch Name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v1
      - name: Install Packages
        run: yarn --prefer-offline
      - name: Run Coverage Tests
        run: yarn test